receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  batch:
    send_batch_size: 50
    timeout: 5s
  memory_limiter:
    ballast_size_mib: 683
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      attributes:
        container_name: "odfe"
        source: "flog"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [ fluentforward ]
      processors: [ memory_limiter, batch ]
      exporters: [ loki ]
